services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    environment:
      DB_HOST: 'idkman'
      DB_USERNAME: root
      DB_PASSWORD: 123456
      DB_DATABASE: kilo_blood
    entrypoint: >
      sh -c "php artisan migrate --seed && php-fpm"
    volumes:
      - .:/var/www
    networks:
      - app_network
    depends_on:
      - mysql
    restart: unless-stopped

  nginx:
    image: nginx:stable-perl
    container_name: nginx
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kilo_blood
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
